source 'https://github.com/CocoaPods/Specs.git'

target 'IVYTraceroute', :exclusive => true do
  pod "IVYTraceroute", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IVYTraceroute", :path => "../"

  
end
